import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        //ENGLISH LANGUAGE
        'en_US': {
          'Login': 'Login',
          'Phone Number': 'Phone Number',
          'Password': 'Password',
          'Forgot': 'Forgot Password?',
          "Don't have an account? ": "Don't have an account? ",
          "Signup here": "Signup here",
          "Signup": "Signup",
          "First Name*": "First Name*",
          "Last Name": "Last Name",
          "Phone Number*": "Phone Number*",
          "Password*": "Password*",
          "Confirm Password*": "Confirm Password*",
          "Confirm Password": "Confirm Password",
          "Referal Code": "Referal Code",
          "Confirm OTP": "Confirm OTP",
          "Confirm": "Confirm",
          "Resend": "Resend",
          "If you didn't get the message tap the resend button bellow.":
              "If you didn't get the message tap the resend button bellow.",
          "Hello, Register here to get started!":
              "Hello, Register here to get started!",
          "Privacy and Security": "Privacy and Security",
          "About Us": "About Us",
          "Change Password": "Change Password",
          "Change Location": "Change Location",
          "Change Language": "Change Language",
          "Logout": "Logout",
          "Email": "Email",
          "Dark Theme": "Dark Theme",
          "Don't worry! It occurs. Please enter the phone number linked with your account":
              "Don't worry! It occurs. Please enter the phone number linked with your account",
          "Send OTP": "Send OTP",
          "OTP Verification": "OTP Verification",
          "Enter the verification code we just sent to your mobile phone":
              "Enter the verification code we just sent to your mobile phone",
          "Verify OTP": "Verify OTP",
          "Create new password?": "Create new password?",
          "Confirm Exit": "Confirm Exit",
          "Do you want to Logout?": "Do you want to Logout?",
          "Yes": "Yes",
          "No": "No",
          "Latest": "Latest",
          "Menu": "Menu",
          "Challenges": "Challenges",
          "Convert Coins": "Convert Coins",
          "Share": "Share",
          "Help": "Help",
          "Rate us": "Rate us",
          "Other products": "Other products",
          "Messages": "Messages",
          "New message1": "New message1",
          "New message2": "New message1",
          "New message3": "New message1",
          "New message4": "New message1",
          "New feature is unlocked": "New feature is unlocked",
          "Total Golden Coins": "Total Golden Coins",
          "Total ATM Coins": "Total ATM Coins",
          "Total Wallet Coins": "Total Wallet Coins",
          "Total MB Coins": "Total MB Coins",
          "Total P Coins": "Total P Coins",
          "Total PC Coins": "Total PC Coins",
          "Total PV Coins": "Total PV Coins",
          "  You have 4.2 Golden coins  ": "  You have 4.2 Golden coins  ",
          "Convert": "Convert",
          "Locations": "Locations",
          "Register": "Register",
          "Languages": "Languages",
        },
        //HINDI LANGUAGE
        'am_ET': {
          'Login': 'ግባ',
          'Phone Number': 'ስልክ ቁጥር',
          'Password': 'የይለፍ ቃል',
          'Forgot': 'መክፈቻ ቁልፉን ረሳኽው?',
          "Don't have an account? ": "መለያ የለዎትም? ",
          "Signup here": "እዚህ ይመዝገቡ",
          "Signup": "ክፈት",
          "First Name*": "የመጀመሪያ ስም*",
          "Last Name": "ያባት ስም",
          "Phone Number*": "ስልክ ቁጥር*",
          "Password*": "የይለፍ ቃል*",
          "Confirm Password*": "የይለፍ ቃል አረጋግጥ*",
          "Confirm Password": "የይለፍ ቃል አረጋግጥ",
          "Reset Password": "የይለፍ ቃል ዳግም አስጀምር",
          "New Password": "አዲስ የይለፍ ቃል",
          "Referal Code": "ሪፈራል ኮድ",
          "Confirm OTP": "OTP ያረጋግጡ",
          "Confirm": "ያረጋግጡ",
          "Reset": "ዳግም አስጀምር",
          "Resend": "እንደገና ላክ",
          "If you didn't get the message tap the resend button bellow.":
              "መልእክቱ ካልደረሰዎት ከታች ያለውን የዳግም ላክ ቁልፍ ይንኩ።",
          "Hello, Register here to get started!": "ሰላም, ለመጀመር እዚህ ይመዝገቡ!",
          "Privacy and Security": "ግላዊነት እና ደህንነት",
          "About Us": "ስለ እኛ",
          "Change Password": "የሚስጥር ቁልፍ ይቀይሩ",
          "Change Language": "ቋንቋ ቀይር",
          "Change Location": "አካባቢን ቀይር",
          "Logout": "ውጣ",
          "Email": "ኢሜይል",
          "Dark Theme": "ጨለማ ጭብጥ",
          "Don't worry! It occurs. Please enter the phone number linked with your account":
              "ይከሰታል። እባክዎ ከመለያዎ ጋር የተገናኘውን ስልክ ቁጥር ያስገቡ",
          "Send OTP": "OTP ላክ",
          "OTP Verification": "የኦቲፒ ማረጋገጫ",
          "Enter the verification code we just sent to your mobile phone":
              "አሁን ወደ ሞባይል ስልኮ የላክነውን የማረጋገጫ ኮድ ያስገቡ",
          "Verify OTP": "ኦቲፒን ያረጋግጡ",
          "Create new password?": "አዲስ የይለፍ ቃል ይፍጠሩ?",
          "Confirm Exit": "መውጣትን ያረጋግጡ",
          "Do you want to Logout?": "መውጣት ትፈልጋለህ?",
          "Yes": "አዎ",
          "No": "አይ",
          "Latest": "የቅርብ ጊዜ",
          "Menu": "ምናሌ",
          "Challenges": "ጨዋታዎች",
          "Convert Coins": "ሳንቲሞችን ይለውጡ",
          "Share": "አጋራ",
          "Help": "እገዛ",
          "Rate us": "ደረጃ ይስጡን",
          "Other products": "ሌሎች ምርቶች",
          "Messages": "መልዕክቶች",
          "New message1": "አዲስ መልእክት1",
          "New message2": "አዲስ መልእክት2",
          "New message3": "አዲስ መልእክት3",
          "New message4": "አዲስ መልእክት4",
          "New feature is unlocked": "አዲስ ባህሪ ተከፍቷል።",
          "Total Golden Coins": "ጠቅላላ Golden ሳንቲሞች",
          "Total ATM Coins": "ጠቅላላ ATM ሳንቲሞች",
          "Total Wallet Coins": "ጠቅላላ Wallet ሳንቲሞች",
          "Total MB Coins": "ጠቅላላ MB ሳንቲሞች",
          "Total P Coins": "ጠቅላላ P ሳንቲሞች",
          "Total PC Coins": "ጠቅላላ PC ሳንቲሞች",
          "Total PV Coins": "ጠቅላላ PV ሳንቲሞች",
          "  You have 4.2 Golden coins  ": "  4.2 Golden ሳንቲሞች አሎት  ",
          "Convert": "ቀይር",
          "Locations": "ቦታዎች",
          "Register": "ይመዝገቡ",
          "Languages": "ቋንቋዎች",
        },
        //KANNADA LANGUAGE
        'or_ET': {
          'Login': 'Senaa',
          'Phone Number': 'Lakkoofsa Bilbilaa',
          'Password': 'Jecha iccitii',
          'Forgot': 'Password dagadheera?',
          "Don't have an account? ": "Akkaawuntii hin qabduu? ",
          "Signup here": "Galmaa'aa",
          "Signup": "Galmaa'i",
          "First Name*": "Maqaa jalqabaa*",
          "Last Name": "Maqaa Abbaa",
          "Phone Number*": "Lakkoofsa Bilbilaa*",
          "Password*": "Jecha iccitii*",
          "Confirm Password*": "Password Mirkaneessi*",
          "Confirm Password": "Password Mirkaneessi",
          "Referal Code": "Koodii Rifaralaa",
          "Confirm OTP": "OTP Mirkaneessuu",
          "Reset": "Reset gochuu",
          "Confirm": "Mirkaneessuu",
          "Reset Password": "Jecha Darbii Irra Deebi'i",
          "New Password": "jecha icciitii haaraa",
          "Resend": "Irra deebiin ergaa",
          "If you didn't get the message tap the resend button bellow.":
              "Yoo ergaan sun hin arganne ta'e button resend armaan gadii tuqi.",
          "Hello, Register here to get started!":
              "Akkam jirtu, Jalqabuuf asitti galmaa'aa!",
          "Privacy and Security": "Dhuunfaa fi Nageenya",
          "About Us": "Waa'ee Keenya",
          "Change Password": "Jecha Darbii Jijjiiri",
          "Change Language": "Afaan Jijjiirraa",
          "Change Location": "Bakka Jijjiirraa",
          "Logout": "Ba'i",
          "Email": "Imeelii",
          "Dark Theme": "Mata Dukkana ",
          "Don't worry! It occurs. Please enter the phone number linked with your account":
              "Ni uuma. Lakkoofsa bilbilaa akkaawuntii keessan waliin walqabate galchaa",
          "Send OTP": "OTP ergaa",
          "OTP Verification": "Mirkaneessa OTP",
          "Enter the verification code we just sent to your mobile phone":
              "Koodii mirkaneessaa amma moobaayila keessaniif erginee galchaa",
          "Verify OTP": "OTP mirkaneessi",
          "Create new password?": "Jecha icciitii haaraa uumuu?",
          "Confirm Exit": "Ba'uu Mirkaneessi",
          "Do you want to Logout?": "Logout gochuu barbaaddaa?",
          "Yes": "Eeyyee",
          "No": "Lakki",
          "Latest": "Kan dhiyeenyaa",
          "Menu": "Filannoo",
          "Challenges": "Taphoota",
          "Convert Coins": "Saantima Jijjiirraa",
          "Share": "Qoodi",
          "Help": "Gargaarsa",
          "Rate us": "Nuuf madaala",
          "Other products": "Oomishaalee Biroo",
          "Messages": "Ergaawwan",
          "New message1": "Ergaa haaraa1",
          "New message2": "Ergaa haaraa2",
          "New message3": "Ergaa haaraa3",
          "New message4": "Ergaa haaraa4",
          "New feature is unlocked": "Amalli haaraan banameera",
          "Total Golden Coins": "Waliigala Saantima Goldani",
          "Total ATM Coins": "Waliigala Saantima ATM",
          "Total Wallet Coins": "Waliigala Saantima Wallet",
          "Total MB Coins": "Waliigala Saantima MB",
          "Total P Coins": "Waliigala Saantima P",
          "Total PC Coins": "Waliigala Saantima PC",
          "Total PV Coins": "Waliigala Saantima PV",
          "  You have 4.2 Golden coins  ": "  Saantima Golden 4.2 qabda  ",
          "Convert": "Jijjiiruu",
          "Locations": "Bakkeewwan",
          "Register": "Galmeessi",
          "Languages": "Afaanota",
        }
      };
}
